[book]
authors = ["VidhosticeSDK"]
description = "Farming Simulator, Blender, Gimp"
language = "cs"
multilingual = false
src = "src"
title = "JZD Vidhostice"

[output.html]
additional-css = ["custom.css"]
