schema_version = "1.0.0"

id = "UDIM_Repack"
version = "1.3.0"
name = "UDIM Repack Toolkit"
tagline = "UDIM Repack Blender Addon"
maintainer = "Paint-a-Farm"
type = "add-on"

website = "https://github.com/Paint-a-Farm/udim-repack"

# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["UV"]

blender_version_min = "2.80.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
license = ["SPDX:GPL-3.0-only"]
